framework:
    secret: '%env(APP_SECRET)%'
    default_locale: fr
    csrf_protection: { enabled: true }
    http_method_override: true
    trusted_hosts: ~
    # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
    session:
        # The native PHP session handler will be used
        handler_id: ~
    esi: { enabled: true }
    fragments: { enabled: true }
    php_errors:
        log: true

