<?php

namespace App\Repository;

/**
 * AlertTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlertTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
