<?php

namespace App\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * BillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Récupération des factures par utilisateurs avec la pagination
     *
     * @param $firstResult
     * @param $perPage
     * @param $id
     * @return Paginator
     */
    public function getBillsByUser($firstResult, $perPage, $id) {
        // Création de l'alias
        $qb = $this->createQueryBuilder('b');

        // Création de la requête personnalisée
        $query = $qb->where('b.user = :user')->orderBy('b.billDate', 'DESC')
            ->setParameter('user', $id)
            ->setFirstResult($firstResult)->setMaxResults($perPage);

        $paginator = new Paginator($query);

        // Récupération du résultat
        return $paginator;
    }
}
