<?php

namespace App\Repository;

/**
 * CountTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
