<?php

namespace App\Repository;

/**
 * CourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Récupération des cours existant entre la date selectionnée et la date +1 heure
     *
     * @param $dateSelected
     * @return mixed
     * @throws \Exception
     */
    public function getExistingCourse($dateSelected) {
        // Création de l'alias
        $qb = $this->createQueryBuilder('c');

        $date = new \DateTime($dateSelected);
        $datePlusOneH = new \DateTime($dateSelected);
        $datePlusOneH->add(new \DateInterval('PT1H'));

        // Création de la requête personnalisée
        $query = $qb->where('c.courseDate BETWEEN :date AND :hour')
            ->setParameter('date', $date)
            ->setParameter('hour', $datePlusOneH);

        return $query->getQuery()->getResult();
    }


    /**
     * Récupération des cours existant du jour sélectionné
     *
     * @param $dateSelected
     * @return mixed
     * @throws \Exception
     */
    public function getCoursesByDay($dateSelected) {
        // Création de l'alias
        $qb = $this->createQueryBuilder('c');

        $dateBegin = new \DateTime($dateSelected);
        $dateEnd = new \DateTime($dateSelected);
        $dateEnd->add(new \DateInterval('PT23H59M59S'));

        dump($dateEnd);

        // Création de la requête personnalisée
        $query = $qb->where('c.courseDate BETWEEN :dayBegin AND :dayEnd')
            ->setParameter('dayBegin', $dateBegin)
            ->setParameter('dayEnd', $dateEnd);

        return $query->getQuery()->getResult();
    }
}
