<?php

namespace App\Repository;

/**
 * CourseCardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseCardRepository extends \Doctrine\ORM\EntityRepository
{
}
