<?php

namespace App\Repository;

/**
 * CourseCardHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseCardHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
