<?php

namespace App\Repository;

/**
 * DayOffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DayOffRepository extends \Doctrine\ORM\EntityRepository
{
}
