<?php

namespace App\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * HorseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HorseRepository extends \Doctrine\ORM\EntityRepository
{
    public function getHorses($firstResult, $perPage) {
        // Création de l'alias
        $qb = $this->createQueryBuilder('h');

        // Création de la requête personnalisée
        $query = $qb->select('h')->setFirstResult($firstResult)->setMaxResults($perPage);

        $paginator = new Paginator($query);

        // Récupération du résultat
        return $paginator;
    }
}
