<?php

namespace App\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Récupération des utilisateurs sans l'administrateur
     *
     * @return array
     */
    public function getUsersExceptAdmin() {
        // Création de l'alias
        $qb = $this->createQueryBuilder('u');

        // Création de la requête personnalisée
        $qb->where('u.roles LIKE :roles')->setParameter('roles', '%ROLE_USER%');

        // Récupération du résultat
        return $qb->getQuery()->getResult();
    }
}
